# Generated by Django 4.2.11 on 2026-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_verified_owner_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('hunter', 'House Hunter'), ('owner', 'Property Owner'), ('mover', 'Mover')], default='hunter', max_length=10),
        ),
    ]
