# Generated by Django 4.2.11 on 2026-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mover_base_label',
            field=models.CharField(blank=True, help_text='Human-readable base location', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='mover_base_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mover_base_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mover_bio',
            field=models.TextField(blank=True, help_text='Public bio shown on your mover profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mover_service_areas',
            field=models.CharField(blank=True, help_text='Comma-separated areas you serve, e.g. Kilimani, Westlands, Karen', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='mover_vehicle_type',
            field=models.CharField(blank=True, choices=[('motorbike', 'Motorbike'), ('pickup', 'Pickup Truck'), ('van', 'Van'), ('truck_small', 'Small Truck'), ('truck_large', 'Large Truck')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='mover_years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
