# Generated by Django 4.2.11 on 2026-07-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_mover_base_label_profile_mover_base_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified_mover',
            field=models.BooleanField(default=False),
        ),
    ]
