# Generated by Django 4.2.11 on 2026-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_verified_mover'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'is_active'], name='users_profi_role_ee642a_idx'),
        ),
    ]
