# Generated by Django 4.2.11 on 2026-07-29 06:02

import Tuhame.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_users_profi_role_ee642a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/pictures/', validators=[Tuhame.upload_validators.validate_profile_picture]),
        ),
    ]
