# Generated by Django 4.2.11 on 2026-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner_about_heading',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_brand_name',
            field=models.CharField(blank=True, help_text='Shown instead of the 2Hame logo on your public profile page.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_marquee_text',
            field=models.CharField(blank=True, help_text='Scrolling announcement text on your public profile, e.g. featured areas or a promo.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_tagline',
            field=models.CharField(blank=True, help_text="Short line shown under your name on your public profile's hero section.", max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_whatsapp_number',
            field=models.CharField(blank=True, help_text='Public WhatsApp number for property inquiries, e.g. 254712345678. Leave blank to hide the WhatsApp button.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
