# Generated by Django 4.2.11 on 2026-08-06 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], db_index=True, default='other', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('location_resolved', models.BooleanField(db_index=True, default=False)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='analytics_p_visited_10fd53_idx'), models.Index(fields=['path', 'visited_at'], name='analytics_p_path_7ae18d_idx'), models.Index(fields=['location_resolved'], name='analytics_p_locatio_db8865_idx')],
            },
        ),
    ]
