# Generated by Django 4.2.11 on 2026-08-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
