# Generated by Django 4.2.11 on 2026-07-29 06:02

import Tuhame.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', validators=[Tuhame.upload_validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signature_file',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/signatures/', validators=[Tuhame.upload_validators.validate_signature_image]),
        ),
    ]
