# Generated by Django 4.2.7 on 2026-05-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("recipients", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=50, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report"),
                            ("weekly", "Weekly Report"),
                            ("monthly", "Monthly Report"),
                            ("yearly", "Yearly Report"),
                            ("custom", "Custom Report"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("generated_for_date", models.DateField(blank=True, null=True)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="reports/pdf/"),
                ),
                (
                    "excel_file",
                    models.FileField(blank=True, null=True, upload_to="reports/excel/"),
                ),
                ("total_properties", models.IntegerField(default=0)),
                ("total_clients", models.IntegerField(default=0)),
                ("total_contracts", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_invoices",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overdue_invoices",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_id"], name="Report_repo_report__e3dba8_idx"
                    ),
                    models.Index(
                        fields=["report_type", "generated_at"],
                        name="Report_repo_report__717e7d_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="Report_repo_start_d_abc669_idx",
                    ),
                    models.Index(
                        fields=["generated_by", "generated_at"],
                        name="Report_repo_generat_d062e6_idx",
                    ),
                ],
            },
        ),
    ]
