# Generated by Django 4.2.11 on 2026-07-29 06:02

import Tuhame.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_bill_billcategory_utilityusage_payment_bill_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='bills/receipts/', validators=[Tuhame.upload_validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/documents/', validators=[Tuhame.upload_validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(upload_to='clients/documents/', validators=[Tuhame.upload_validators.validate_document]),
        ),
    ]
