# Generated by Django 4.2.11 on 2026-07-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_bill_billcategory_utilityusage_payment_bill_category_and_more'),
        ('properties', '0002_propertyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client'),
        ),
    ]
