# Generated by Django 4.2.11 on 2026-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_booking_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'status'], name='properties__is_acti_fad349_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
    ]
