# Generated by Django 4.2.11 on 2026-07-29 06:02

import Tuhame.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_properties__is_acti_fad349_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/main/', validators=[Tuhame.upload_validators.validate_property_image]),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/gallery/', validators=[Tuhame.upload_validators.validate_property_image]),
        ),
    ]
