# Generated by Django 4.2.11 on 2026-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_main_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'is_active'], name='properties__owner_i_a56902_idx'),
        ),
    ]
