# Generated by Django 4.2.7 on 2026-07-12 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_propertyreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_savedproperty"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moving_from", models.TextField()),
                (
                    "moving_to_manual",
                    models.TextField(
                        blank=True, help_text="If not selecting a property"
                    ),
                ),
                ("move_date", models.DateField()),
                (
                    "move_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (8am-12pm)"),
                            ("afternoon", "Afternoon (12pm-5pm)"),
                            ("evening", "Evening (5pm-8pm)"),
                        ],
                        default="afternoon",
                        max_length=20,
                    ),
                ),
                (
                    "items",
                    models.JSONField(default=list, help_text="List of items to move"),
                ),
                (
                    "items_list",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list for display",
                        max_length=500,
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                ("request_mover", models.BooleanField(default=False)),
                ("movers_count", models.IntegerField(default=2)),
                ("estimated_hours", models.IntegerField(default=4)),
                ("mover_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moving_to_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="move_in_requests",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
