# Generated by Django 4.2.7 on 2026-07-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_moverequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="moverequest",
            name="moving_from_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="moverequest",
            name="moving_from_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="moverequest",
            name="moving_to_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="moverequest",
            name="moving_to_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
