# Generated by Django 4.2.11 on 2026-07-18 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('matched', 'Matched With Mover'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MoveOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn by Mover')], default='pending', max_length=12)),
                ('mover_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('mover_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='home.moverequest')),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'price', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='moveoffer',
            constraint=models.UniqueConstraint(fields=('move_request', 'mover'), name='one_offer_per_mover_per_request'),
        ),
    ]
