# Generated by Django 4.2.11 on 2026-07-16 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('hunter', 'House Hunter'), ('owner', 'Property Owner')], default='hunter', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes, e.g. reason for rejection'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_owner_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
    ]
