# Generated by Django 5.2.16 on 2026-07-30 09:55

import Tuhame.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_moverequest_status_moveoffer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional — a default placeholder icon is shown if left blank.",
                        null=True,
                        upload_to="partners/logos/",
                        validators=[Tuhame.upload_validators.validate_partner_logo],
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Where clicking the logo should send visitors.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
