# Generated by Django 4.2.11 on 2026-08-27 20:09

import Tuhame.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Headline shown over the slide. Basic HTML like <em>Home</em> is allowed for the highlighted word — it's rendered as-is.", max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Used when Media type is Image.', null=True, upload_to='hero/images/', validators=[Tuhame.upload_validators.validate_hero_image])),
                ('video', models.FileField(blank=True, help_text='Used when Media type is Video. Compressed and re-encoded automatically on save (muted, max 30s, 1080p) — the original file you upload is not what gets stored.', null=True, upload_to='hero/videos/', validators=[Tuhame.upload_validators.validate_hero_video])),
                ('video_poster', models.ImageField(blank=True, help_text='Optional still frame shown while the video loads. Auto-generated from the video if left blank and the server supports it.', null=True, upload_to='hero/video_posters/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
