# Generated by Django 4.2.11 on 2026-07-30 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('excerpt', models.CharField(blank=True, help_text='Short teaser shown on the blog list and used as a fallback meta description.', max_length=300)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('category', models.CharField(choices=[('market-insights', 'Market Insights'), ('renting-tips', 'Renting Tips'), ('landlord-guides', 'Landlord Guides'), ('moving-guides', 'Moving Guides'), ('neighborhood-guides', 'Neighborhood Guides'), ('company-news', '2Hame News')], default='market-insights', max_length=30)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Nairobi, first apartment, moving tips'.", max_length=255)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides the page <title>. Falls back to the post title if left blank.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Meta description. Falls back to the excerpt if left blank.', max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='blog_blogpo_publish_e75c11_idx'), models.Index(fields=['is_published'], name='blog_blogpo_is_publ_c847aa_idx'), models.Index(fields=['category'], name='blog_blogpo_categor_481d67_idx')],
            },
        ),
    ]
