# Generated by Django 4.2.7 on 2026-05-24 07:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("buyer", "Buyer"),
                            ("owner", "Property Owner"),
                            ("agent", "Real Estate Agent"),
                            ("investor", "Investor"),
                        ],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        help_text="Passport, Driver's License, etc.",
                        max_length=50,
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=100)),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="clients/documents/"
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("employer", models.CharField(blank=True, max_length=200)),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "preferred_property_types",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("preferred_locations", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id", "Identification"),
                            ("income", "Income Proof"),
                            ("employment", "Employment Letter"),
                            ("reference", "Reference"),
                            ("contract", "Contract"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="clients/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to="clients.client",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_by",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "property")},
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["client_type"], name="clients_cli_client__1e0f73_idx"
            ),
        ),
    ]
