"""
Django settings for Tuhame project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the old insecure key only in local dev so the project still
# boots without a .env file. ALWAYS set SECRET_KEY in your environment/.env
# before deploying anywhere real.
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-$sh_r03e35qx-nl9u!k0(!gfa!3=7ynmuxg0hbh@ga&^w8xqak'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Comma separated list in .env, e.g. ALLOWED_HOSTS=tuhame.co.ke,www.tuhame.co.ke
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='*' if DEBUG else '',
    cast=lambda v: [h.strip() for h in v.split(',') if h.strip()]
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'home',
    'users',
    'dashboard',
    'properties',
    'clients',
    'contracts',
    'payments',
    'Report',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tuhame.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "templates"],
        # APP_DIRS and OPTIONS['loaders'] are mutually exclusive in Django,
        # so app-dirs scanning is folded into the loader list below whenever
        # we override loaders (production only — dev keeps auto-reload).
        'APP_DIRS': DEBUG,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            **({} if DEBUG else {
                # Cached loader: each template is compiled once per worker
                # process and reused, instead of being re-read + re-parsed
                # from disk on every single request.
                'loaders': [
                    ('django.template.loaders.cached.Loader', [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ]),
                ],
            }),
        },
    },
]

WSGI_APPLICATION = 'Tuhame.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Reuse DB connections across requests instead of opening/closing one
        # every time (biggest win once you move off SQLite to Postgres/MySQL,
        # where connection setup is the expensive part — harmless here too).
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
    }
}

# ========== PRODUCTION DATABASE ==========
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'daysafaris_daysafarisadventure',
#         'USER': 'daysafaris_sudo',
#         'PASSWORD': '@D4y54f4r15',
#         'HOST': 'localhost',
#         'PORT': '5432',
        #     'OPTIONS': {
        #     'connect_timeout': 10,
        #     'options': '-c statement_timeout=5000ms',
        # },
#     }
# }

# # ========== mysql DATABASE ==========
# DATABASES = {
#     'default': {
#         'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
#         'NAME': config('DB_NAME', default='daysafaris_daysafarisadventure'),
#         'USER': config('DB_USER', default='daysafaris_sudo'),
#         'PASSWORD': config('DB_PASSWORD', default=''),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='3306'),
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#         },
#         'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=600, cast=int),
#         'ATOMIC_REQUESTS': config('DB_ATOMIC_REQUESTS', default=True, cast=bool),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='Africa/Nairobi')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = "staticfiles"

STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'

import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Compressed, cache-busted static files: each file gets a content hash in
# its name (so browsers can cache it "forever") and is pre-gzipped/brotli'd
# at collectstatic time instead of being compressed on every request.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "Tuhame.storage.LenientCompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_MAX_AGE = 31536000  # 1 year — safe because filenames are hashed

# ============ CACHING ============
# Uses Redis when REDIS_URL is set (recommended for production — a shared
# cache across multiple gunicorn workers/servers). Falls back to a local
# in-memory cache otherwise, so caching still helps in dev/single-process
# setups with zero extra infrastructure required.
REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'tuhame-cache',
            'TIMEOUT': 300,
            'OPTIONS': {'MAX_ENTRIES': 5000},
        }
    }

# Sessions read/write through the cache first (falling back to the DB), so
# a logged-in user's session lookup is usually a cache hit instead of a
# query on every single request.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# config/settings.py - Add these settings

# Login/Logout URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home:home'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Comma separated list in .env, e.g.
# CSRF_TRUSTED_ORIGINS=https://tuhame.co.ke,https://www.tuhame.co.ke
# Add your ngrok/dev tunnel URL here locally instead of hardcoding it.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [h.strip() for h in v.split(',') if h.strip()]
)

# Used to build absolute URLs (QR codes, emails, share links). Falls back to
# localhost in dev so the app doesn't crash if .env is missing SITE_URL.
SITE_URL = config("SITE_URL", default="http://127.0.0.1:8000")

# ============ EMAIL (used for notifications e.g. move requests, viewings) ============
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='TuHame <no-reply@tuhame.co.ke>')

# ============ PRODUCTION SECURITY HARDENING ============
# These only kick in when DEBUG=False (i.e. on your live server), so local
# development over plain http:// keeps working exactly as before.
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week, raise once confirmed working
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'